export const levels = [
    { // 1
        seed: 0,
        width: 10,
        height: 10,
        tiles: 2,
        text_color: "#f88",
        shadow_color: "#f00",
    },
    { // 2
        seed: 1,
        width: 15,
        height: 15,
        tiles: 3,
        text_color: "#8f8",
        shadow_color: "#0f0",
    },
    { // 3
        seed: 2,
        width: 22,
        height: 22,
        tiles: 4,
        text_color: "#88f",
        shadow_color: "#00f",
    },
    { // 4
        seed: 3,
        width: 33,
        height: 33,
        tiles: 5,
        text_color: "#8ff",
        shadow_color: "#0aa",
    },
    { // 5
        seed: 4,
        width: 49,
        height: 49,
        tiles: 6,
        text_color: "#f8f",
        shadow_color: "#a0a",
    },
    { // 6
        seed: 6,
        width: 73,
        height: 73,
        tiles: 6,
        dither: 1,
        text_color: "#ff8",
        shadow_color: "#aa0",
    },
    { // 7
        seed: 9,
        width: 109,
        height: 109,
        tiles: 6,
        dither: 2,
        text_color: "#fa7",
        shadow_color: "#f80",
    },
    { // 8
        seed: 16,
        width: 119,
        height: 119,
        tiles: 6,
        dither: 0,
        text_color: "#a00",
        shadow_color: "#600",
        maze: true,
    },
];